name: Aragoncraft
version: '${version}'
main: net.aragoncraft.plugin
api-version: 1.19
depend:
  - Vault
  - LuckPerms
authors:
  - MythicXGN
  - Jpuf
commands:
  balance:
    usage: /balance
    aliases: bal
    description: adds to a Players Balance
